import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { PGlite } from '@electric-sql/pglite';
const reader = '10000000-0000-4000-8000-000000000001';
const books = [{ googleBookId: 'one', title: 'One', authors: ['Author'], coverUrl: null }, { googleBookId: 'two', title: 'Two', authors: ['Author'], coverUrl: null }];
const db = new PGlite();
await db.exec(`create role anon; create role authenticated; create schema auth;
create function auth.uid() returns uuid language sql as $$select '${reader}'::uuid$$;
create function public.novori_account_active(uuid) returns boolean language sql as $$select true$$;
create function public.novori_reader_restricted(uuid) returns boolean language sql as $$select false$$;
create table book_stacks(id uuid primary key default gen_random_uuid(),user_id uuid,name text,visibility text,created_at timestamptz default now(),updated_at timestamptz default now());
create table book_stack_items(id uuid primary key default gen_random_uuid(),stack_id uuid references book_stacks(id) on delete cascade,google_book_id text,title text check(title<>'INVALID'),authors text[],cover_url text,position int,created_at timestamptz default now());
create table posts(id uuid primary key default gen_random_uuid(),author_id uuid,club_id uuid,post_type text,body text check(body<>'FAIL_POST'),book_stack_id uuid references book_stacks(id),updated_at timestamptz default now());`);
await db.exec(await readFile(new URL('../../supabase/migrations/20261006180000_atomic_book_stack.sql', import.meta.url), 'utf8'));
const save = (name, items, id = null, publish = false, body = '', postId = null) => db.query('select novori_save_book_stack($1,$2,$3,$4,$5,null,$6) result', [name, JSON.stringify(items), id, publish, body, postId]);
test('item or post failure cannot leave a newly created empty stack', async () => {
  await assert.rejects(save('Failed books', [books[0], { ...books[1], title: 'INVALID' }]));
  await assert.rejects(save('Failed post', books, null, true, 'FAIL_POST'));
  assert.equal((await db.query('select count(*)::int n from book_stacks')).rows[0].n, 0);
  assert.equal((await db.query('select count(*)::int n from book_stack_items')).rows[0].n, 0);
});
test('complete stack and post commit together; failed edits preserve the original', async () => {
  const stack = (await save('Original', books, null, true, 'Safe caption')).rows[0].result;
  assert.equal(stack.items.length, 2);
  const post = (await db.query('select * from posts where book_stack_id=$1', [stack.id])).rows[0];
  await assert.rejects(save('Changed', [books[0], { ...books[1], title: 'INVALID' }], stack.id));
  await assert.rejects(save('Changed', books, stack.id, true, 'FAIL_POST', post.id));
  assert.equal((await db.query('select name from book_stacks where id=$1', [stack.id])).rows[0].name, 'Original');
  assert.equal((await db.query('select count(*)::int n from book_stack_items where stack_id=$1', [stack.id])).rows[0].n, 2);
  assert.equal((await db.query('select body from posts where id=$1', [post.id])).rows[0].body, 'Safe caption');
  await assert.rejects(save('Wrong owner', books, '10000000-0000-4000-8000-000000000099'));
});
