import { displayBookTitle } from '../lib/book-title';
import { Ionicons } from '@expo/vector-icons';
import { useFocusEffect,useRouter } from 'expo-router';
import { useCallback,useRef,useState } from 'react';
import { Pressable,Text,View } from 'react-native';
import { useNovoriTheme } from '../context/theme-context';
import { getClubDiscussion,voteClubPoll,closeClubPoll } from '../lib/club-discussions';
import { discussionRevealKey,type ClubDiscussion } from '../lib/club-discussion';
import BookCoverImage from './BookCoverImage';
import ValidationWarningSheet from './ValidationWarningSheet';
import DeletePostConfirmSheet from './DeletePostConfirmSheet';

export default function ClubDiscussionPostAttachment({discussion,detail=false,revealed,onReveal,onStateChange}:{discussion:ClubDiscussion;detail?:boolean;revealed?:boolean;onReveal?:()=>void;onStateChange?:(row:ClubDiscussion)=>void}) {
  const router=useRouter(),{colors}=useNovoriTheme();const [state,setState]=useState(discussion),[localReveal,setLocalReveal]=useState(''),[busy,setBusy]=useState(false),[warning,setWarning]=useState(''),[closing,setClosing]=useState(false);
  const active=useRef(true),mutationBusy=useRef(false),stateChange=useRef(onStateChange);stateChange.current=onStateChange;const key=discussionRevealKey(discussion);
  useFocusEffect(useCallback(()=>{let current=true;active.current=true;setState(discussion);if(detail)void getClubDiscussion(discussion.id).then(row=>{if(current&&active.current){setState(row);if(row.updated_at!==discussion.updated_at)stateChange.current?.(row);}}).catch(error=>{if(current&&active.current)setWarning(error?.message||'Could not refresh this discussion.');});return()=>{current=false;active.current=false;};},[discussion,detail]));
  const hidden=state.contains_spoilers&&!(revealed??localReveal===key);
  const count=state.vote_counts?.reduce((sum,n)=>sum+n,0)??0;
  async function vote(choice:number){if(mutationBusy.current)return;mutationBusy.current=true;setBusy(true);try{const row=await voteClubPoll(state.id,state.viewer_choice===choice?null:choice);if(active.current)setState(row);}catch(error){if(active.current)setWarning((error as {message?:string})?.message||'Could not save your vote.');}finally{mutationBusy.current=false;if(active.current)setBusy(false);}}
  async function close(){if(mutationBusy.current)return;mutationBusy.current=true;setBusy(true);try{await closeClubPoll(state.id);const row=await getClubDiscussion(state.id);if(active.current){setState(row);setClosing(false);}}catch(error){if(active.current){setClosing(false);setWarning((error as {message?:string})?.message||'Could not close the poll.');}}finally{mutationBusy.current=false;if(active.current)setBusy(false);}}
  const copy={color:colors.secondaryText,fontFamily:'Inter_400Regular',fontSize:12,lineHeight:19};
  return <View style={{marginTop:9,borderWidth:1,borderColor:`${colors.gold}40`,borderRadius:17,backgroundColor:colors.surface,overflow:'hidden'}}><View style={{height:3,backgroundColor:colors.gold}}/><View style={{padding:14}}>
    <Text style={{color:colors.gold,fontFamily:'Inter_700Bold',fontSize:10,letterSpacing:.7,marginBottom:9}}>{state.kind==='poll'?'CLUB POLL':'BOOK DISCUSSION'}{state.closed_at?' · CLOSED':''}</Text>
    {state.book?<View style={{flexDirection:'row',alignItems:'center',gap:11,marginBottom:12}}><BookCoverImage googleBookId={state.book.googleBookId} isbn={state.book.isbn} existingCoverUrl={state.book.coverUrl} style={{width:39,height:59,borderRadius:5}}/><View style={{flex:1}}><Text style={{...copy,color:colors.text,fontFamily:'Inter_600SemiBold'}}>{displayBookTitle(state.book.title ?? '')}</Text><Text style={{...copy,color:colors.mutedText,fontSize:10}}>{state.book.authors.join(', ')}</Text></View></View>:null}
    {hidden?<View><Ionicons name="eye-off-outline" size={22} color={colors.gold}/><Text style={{...copy,color:colors.text,fontFamily:'Inter_600SemiBold',marginTop:6}}>This thread contains spoilers</Text><Text style={{...copy,color:colors.mutedText,marginTop:4}}>{state.spoiler_label}</Text><Text style={{...copy,color:colors.mutedText,fontSize:11,marginTop:4}}>The discussion and its comments stay hidden until you reveal them.</Text><Pressable accessibilityRole="button" accessibilityLabel="Reveal club discussion spoilers" onPress={()=>{setLocalReveal(key);onReveal?.();}} style={{paddingVertical:12}}><Text style={{...copy,color:colors.gold,fontFamily:'Inter_600SemiBold'}}>Reveal discussion</Text></Pressable></View>:<>
      {state.contains_spoilers?<Text style={{...copy,color:colors.gold,fontSize:10,marginBottom:8}}>SPOILERS · {state.spoiler_label}</Text>:null}
      <Text style={{color:colors.text,fontFamily:'PlayfairDisplay_700Bold',fontSize:23,lineHeight:29}}>{state.title}</Text>{state.prompt?<Text style={{...copy,marginTop:10}} numberOfLines={detail?undefined:4}>{state.prompt}</Text>:null}
      {state.kind==='poll'?<View style={{marginTop:12}}>{detail?state.options.map((option,i)=>{const votes=state.vote_counts?.[i]??0,percent=count?Math.round(votes/count*100):0;return <Pressable key={i} disabled={busy||Boolean(state.closed_at)||!state.viewer_is_member} accessibilityRole="button" accessibilityLabel={`Vote: ${option}`} accessibilityState={{selected:state.viewer_choice===i}} onPress={()=>void vote(i)} style={{minHeight:45,padding:11,marginBottom:7,borderWidth:1,borderColor:state.viewer_choice===i?colors.gold:colors.border,borderRadius:10,overflow:'hidden'}}><View pointerEvents="none" style={{position:'absolute',left:0,top:0,bottom:0,width:`${percent}%`,backgroundColor:`${colors.gold}16`}}/><View style={{flexDirection:'row',gap:8,alignItems:'center'}}><Text style={{...copy,color:colors.text,flex:1,fontFamily:'Inter_600SemiBold'}}>{option}</Text><Text style={{...copy,fontSize:10}}>{percent}% · {votes}</Text>{state.viewer_choice===i?<Ionicons name="checkmark-circle" size={16} color={colors.gold}/>:null}</View></Pressable>;}):<Text style={copy}>{state.options.length} choices · Open the poll to vote</Text>}{detail?<Text style={{...copy,color:colors.mutedText,fontSize:10}}>{count} {count===1?'vote':'votes'} · {state.closed_at?'Voting closed':state.viewer_is_member?'Tap your choice again to clear your vote':'Join this club to vote'}</Text>:null}</View>:null}
    </>}
    {!detail?<Pressable accessibilityRole="button" accessibilityLabel="Open club discussion" onPress={()=>router.push({pathname:'/post/[id]',params:{id:state.post_id}})} style={{paddingVertical:12}}><Text style={{...copy,color:colors.gold,fontFamily:'Inter_600SemiBold'}}>Open {state.kind==='poll'?'poll':'discussion'}</Text></Pressable>:state.viewer_can_manage?<View style={{flexDirection:'row',gap:17,marginTop:10}}>{!(state.kind==='poll'&&(state.voting_started_at||state.closed_at))?<Pressable accessibilityRole="button" accessibilityLabel="Edit club discussion" onPress={()=>router.push({pathname:'/create-club-discussion',params:{clubId:state.club_id,discussionId:state.id}})} style={{paddingVertical:9}}><Text style={{...copy,color:colors.gold}}>Edit</Text></Pressable>:null}{state.kind==='poll'&&!state.closed_at?<Pressable disabled={busy} accessibilityRole="button" accessibilityLabel="Close club poll" onPress={()=>setClosing(true)} style={{paddingVertical:9}}><Text style={{...copy,color:colors.gold}}>Close poll</Text></Pressable>:null}</View>:null}
    <DeletePostConfirmSheet visible={closing} busy={busy} title="Close this poll?" message="The results will stay visible. Members will no longer be able to vote or change their choice." confirmLabel="Close poll" cancelLabel="Keep open" onDismiss={()=>{if(!busy)setClosing(false);}} onConfirm={close}/>
    <ValidationWarningSheet visible={Boolean(warning)} title="Club discussion" message={warning} onDismiss={()=>setWarning('')}/>
  </View></View>;
}
