import React from 'react';
import renderer,{act} from 'react-test-renderer';
import AuthScreen from '../src/app/auth';
import {supabase} from '../src/lib/supabase';
import {getAccountDeletionStatus} from '../src/lib/account-deletion';
const mockRouter={replace:jest.fn(),push:jest.fn()};
jest.mock('expo-router',()=>({useRouter:()=>mockRouter}));
jest.mock('react-native',()=>({Platform:{OS:'ios',select:v=>v.ios??v.default},TurboModuleRegistry:{get:()=>null},Keyboard:{addListener:()=>({remove:jest.fn()}),dismiss:jest.fn()},ActivityIndicator:'ActivityIndicator',Pressable:'Pressable',View:'View',Text:'Text',ScrollView:'ScrollView',TextInput:'TextInput',StyleSheet:{create:v=>v},Alert:{alert:jest.fn()}}));
jest.mock('react-native-safe-area-context',()=>({SafeAreaView:'SafeAreaView'}));
jest.mock('../src/components/ValidationWarningSheet',()=> 'ValidationWarningSheet');
jest.mock('../src/context/theme-context',()=>({useNovoriTheme:()=>({colors:require('../src/constants/novori-theme').DARK_COLORS})}));
jest.mock('../src/lib/supabase',()=>({supabase:{auth:{signInWithPassword:jest.fn()}}}));
jest.mock('../src/lib/account-deletion',()=>({getAccountDeletionStatus:jest.fn()}));
let view,silence;
beforeEach(()=>{globalThis.IS_REACT_ACT_ENVIRONMENT=true;jest.clearAllMocks();supabase.auth.signInWithPassword.mockResolvedValue({error:null});getAccountDeletionStatus.mockResolvedValue({state:'active'});silence=jest.spyOn(console,'error').mockImplementation(()=>{});});
afterEach(async()=>{if(view)await act(async()=>view.unmount());view=null;silence.mockRestore();});
async function submit(){await act(async()=>{view=renderer.create(<AuthScreen/>);});for(const [placeholder,value] of [['Email','reader@example.com'],['Password','password123']])await act(async()=>view.root.findAllByType('TextInput').find(n=>n.props.placeholder===placeholder).props.onChangeText(value));await act(async()=>view.root.findAllByType('Pressable').find(n=>n.findAllByType('Text').some(t=>t.props.children==='Sign In')).props.onPress());}
test('a paused account signs directly into deletion instead of briefly mounting Home',async()=>{getAccountDeletionStatus.mockResolvedValue({state:'pending'});await submit();expect(mockRouter.replace).toHaveBeenCalledWith('/delete-account');});
test('an active account still opens Home',async()=>{await submit();expect(mockRouter.replace).toHaveBeenCalledWith('/(tabs)');});
test('invalid deleted-account credentials use the animated Novori warning',async()=>{supabase.auth.signInWithPassword.mockResolvedValue({error:new Error('Invalid login credentials')});await submit();expect(view.root.findByType('ValidationWarningSheet').props).toMatchObject({visible:true,title:'Could not sign in',message:'Invalid login credentials'});expect(mockRouter.replace).not.toHaveBeenCalled();});
