const fs=require('fs'),path=require('path'),vm=require('vm'),ts=require('typescript');
function load(file,requireFn=()=>{throw Error('Unexpected provider dependency')}){const exports={};vm.runInNewContext(ts.transpileModule(fs.readFileSync(path.join(__dirname,'../src/lib/',file),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{exports,require:requireFn,Date,Error,Intl});return exports;}
const pure=load('club-discussion.ts');const d={id:'topic',post_id:'post-1',club_id:'club-1',read_id:'read-1',kind:'poll',title:'Next book?',prompt:'Choose together.',contains_spoilers:true,spoiler_label:'Whole book',options:['A','B'],closed_at:null,voting_started_at:null,updated_at:'2026-10-03',book:{googleBookId:'cached-book',title:'Book',authors:['Author'],coverUrl:'stored-cover'}};
function harness(data=d,error=null){const calls=[],mutations=[],supabase={rpc:async(name,args)=>{calls.push({name,args});return{data,error};}};return{calls,mutations,api:load('club-discussions.ts',name=>name==='./supabase'?{supabase}:name==='./club-discussion'?pure:name==='./feed'?{markPostMutation:()=>mutations.push(true)}:(()=>{throw Error('Cover/provider import '+name)})())};}
test('topic reads preserve stored book identity and pages use only one database RPC',async()=>{const h=harness();expect(await h.api.getClubDiscussion('topic')).toEqual(d);expect(h.calls).toEqual([{name:'get_club_discussion',args:{target_discussion_id:'topic'}}]);const page=harness([d]);expect(await page.api.getClubDiscussions('club-1','read-1','poll',20)).toEqual([d]);expect(page.calls[0].args).toEqual({target_club_id:'club-1',target_read_id:'read-1',discussion_scope:'poll',page_offset:20,result_limit:20});});
test('transactional saves carry edit revision and stable draft retry key',async()=>{const h=harness('post-1');await h.api.saveClubDiscussion('club-1',{...d,title:' Next book? '},undefined,'stable-request-key');expect(h.calls[0].args).toMatchObject({request_key:'stable-request-key',target_discussion_id:null,discussion_input:{title:'Next book?'}});await h.api.saveClubDiscussion('club-1',d,d);expect(h.calls[1].args.expected_updated_at).toBe(d.updated_at);expect(h.mutations).toEqual([true,true]);});
test.each([{title:'x'},{kind:'bad'},{options:['A']},{options:['A','a']},{options:['A','']},{spoiler_label:''},{prompt:'x'.repeat(3001)},{kind:'discussion',prompt:''}])('invalid topics make no database request: %o',async change=>{const h=harness();await expect(h.api.saveClubDiscussion('club-1',{...d,...change})).rejects.toThrow();expect(h.calls).toEqual([]);});
test('votes return confirmed counts, can clear the selection, and close invalidates post views',async()=>{const h=harness({...d,vote_counts:[1,0],viewer_choice:0});expect((await h.api.voteClubPoll('topic',0)).vote_counts).toEqual([1,0]);await h.api.voteClubPoll('topic',null);expect(h.calls[1].args.choice_index).toBeNull();expect(h.mutations).toEqual([]);await h.api.closeClubPoll('topic');expect(h.mutations).toEqual([true]);});
test('permission failures never confirm writes or mutate feed state',async()=>{const h=harness(null,new Error('Permission changed'));await expect(h.api.saveClubDiscussion('club-1',d)).rejects.toThrow('Permission changed');await expect(h.api.voteClubPoll('topic',0)).rejects.toThrow('Permission changed');await expect(h.api.closeClubPoll('topic')).rejects.toThrow('Permission changed');expect(h.mutations).toEqual([]);});
test('spoiler previews never expose topic titles, and revised content gets a new reveal key',()=>{expect(pure.clubDiscussionPreview(d)).toBe('Spoiler-marked poll');expect(pure.clubDiscussionPreview({...d,contains_spoilers:false})).toBe(d.title);expect(pure.discussionRevealKey({...d,updated_at:'new'})).not.toBe(pure.discussionRevealKey(d));});
test('discussion editing is type aware',()=>{const routes=load('post-edit-route.ts');expect(routes.getPostEditRoute({id:'post-1',club_discussion:d})).toEqual({pathname:'/create-club-discussion',params:{clubId:'club-1',discussionId:'topic'}});});
